# Generated by Django 3.2.8 on 2021-11-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('request_index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=30)),
                ('ori_img_path', models.CharField(max_length=100)),
                ('result_img_path', models.CharField(max_length=100)),
                ('detected_numbers', models.IntegerField(default=0)),
                ('is_response', models.BooleanField(default=False)),
                ('selected_pn_index', models.IntegerField(default=-1)),
                ('called_number', models.CharField(max_length=15)),
                ('timestamp1', models.IntegerField(default=-1)),
                ('timestamp2', models.IntegerField(default=-1)),
                ('timestamp3', models.IntegerField(default=-1)),
                ('timestamp4', models.IntegerField(default=-1)),
                ('root_request_index', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['request_index'],
            },
        ),
        migrations.CreateModel(
            name='DetectedNumbers',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number_index', models.IntegerField()),
                ('is_area_code', models.BooleanField(default=False)),
                ('n_candidates', models.IntegerField(default=-1)),
                ('pos1_x', models.FloatField()),
                ('pos1_y', models.FloatField()),
                ('pos2_x', models.FloatField()),
                ('pos2_y', models.FloatField()),
                ('pos3_x', models.FloatField()),
                ('pos3_y', models.FloatField()),
                ('pos4_x', models.FloatField()),
                ('pos4_y', models.FloatField()),
                ('request_index', models.ForeignKey(db_column='request_index', on_delete=django.db.models.deletion.CASCADE, related_name='googlestar_request_info', to='googlestar.requestinfo')),
            ],
            options={
                'ordering': ['request_index', 'number_index'],
                'unique_together': {('request_index', 'number_index')},
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_index', models.IntegerField()),
                ('is_area_code', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=15)),
                ('detected_index', models.ForeignKey(db_column='index', on_delete=django.db.models.deletion.CASCADE, related_name='googlestar_detectednumbers', to='googlestar.detectednumbers')),
            ],
            options={
                'ordering': ['detected_index', 'candidate_index'],
                'unique_together': {('detected_index', 'candidate_index')},
            },
        ),
    ]
