# Generated by Django 3.2.8 on 2021-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlestar', '0003_rename_index_detectednumbers_detected_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectednumbers',
            name='n_candidates',
            field=models.IntegerField(default=0),
        ),
    ]
