# Generated by Django 3.2.8 on 2021-11-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlestar', '0004_alter_detectednumbers_n_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='detected_index',
            field=models.ForeignKey(db_column='detected_index', on_delete=django.db.models.deletion.CASCADE, related_name='googlestar_detectednumbers', to='googlestar.detectednumbers'),
        ),
    ]
