# Generated by Django 3.2.8 on 2021-11-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlestar', '0005_alter_candidates_detected_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='called_number',
            field=models.CharField(max_length=30),
        ),
    ]
